author:
  name: "Mabior Deng Kuer Mabior"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD Student in Aviation and Aerospace"
  location: "West Lafayette, IN, USA"

  links:
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/files/Mabior_CV.pdf"

    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "#"

    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "#"

    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "#"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "#"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MabiorAero"

    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:Mabiordengkuer@yahoo.com"
