title: "Mabior Deng Kuer Mabior"
email: "Mabiordengkuer@yahoo.com"
description: "Academic website and research portfolio"

minimal_mistakes_skin: "default"
search: true

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name: "Mabior Deng Kuer Mabior"
  avatar: "/assets/images/profile.jpg"
  bio: "PhD Student in Aviation and Aerospace"
  location: "West Lafayette, Indiana, USA"

  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "#"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MabiorAero"

    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:Mabiordengkuer@yahoo.com"

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MabiorAero"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
